config/routes.rb
Animales::Application.routes.draw do
  get "user/currentUser"

  get "users/currentUser"

  resources :formularios

  devise_for :admins

  resources :admins

  devise_for :protectoras

  get "display/index"

  devise_for :users, :controllers => { :omniauth_callbacks => "display#facebook" }

  resources :protectoras

  resources :mascota
  
  root :to => 'display#index'

end

app/models/formulario.rb
class Formulario < ActiveRecord::Base
  belongs_to :usuario , :class_name => "User", :foreign_key => :usuario_id  
  belongs_to :mascota , :class_name => "Mascotum", :foreign_key => :mascota_id  
  
  
end

app/controllers/formularios_controller.rb
class FormulariosController < ApplicationController
  # GET /formularios
  # GET /formularios.json
  def index
    @formularios = Formulario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @formularios }
    end
  end

  # GET /formularios/1
  # GET /formularios/1.json
  def show
    @formulario = Formulario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @formulario }
    end
  end

  # GET /formularios/new
  # GET /formularios/new.json
  def new
    @formulario = Formulario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @formulario }
    end
  end

  # GET /formularios/1/edit
  def edit
    @formulario = Formulario.find(params[:id])
  end

  # POST /formularios
  # POST /formularios.json
  def create
    @formulario = Formulario.new(params[:formulario])

    respond_to do |format|
      if @formulario.save
        format.html { redirect_to @formulario, notice: 'Formulario was successfully created.' }
        format.json { render json: @formulario, status: :created, location: @formulario }
      else
        format.html { render action: "new" }
        format.json { render json: @formulario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /formularios/1
  # PUT /formularios/1.json
  def update
    @formulario = Formulario.find(params[:id])

    respond_to do |format|
      if @formulario.update_attributes(params[:formulario])
        format.html { redirect_to @formulario, notice: 'Formulario was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @formulario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formularios/1
  # DELETE /formularios/1.json
  def destroy
    @formulario = Formulario.find(params[:id])
    @formulario.destroy

    respond_to do |format|
      format.html { redirect_to formularios_url }
      format.json { head :ok }
    end
  end
end

app/helpers/formularios_helper.rb
module FormulariosHelper
end

app/views/formularios/_form.html.erb
<%= form_for(@formulario) do |f| %>
  <% if @formulario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@formulario.errors.count, "error") %> prohibited this formulario from being saved:</h2>

      <ul>
      <% @formulario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mascota_id %><br />
    <%= f.text_field :mascota_id %>
  </div>
  <div class="field">
    <%= f.label :usuario_id %><br />
    <%= f.text_field :usuario_id %>
  </div>
  <div class="field">
    <%= f.label :revisado %><br />
    <%= f.check_box :revisado %>
  </div>
  <div class="field">
    <%= f.label :aceptado %><br />
    <%= f.check_box :aceptado %>
  </div>
  <div class="field">
    <%= f.label :ocupacion %><br />
    <%= f.text_field :ocupacion %>
  </div>
  <div class="field">
    <%= f.label :dependencia %><br />
    <%= f.text_field :dependencia %>
  </div>
  <div class="field">
    <%= f.label :autorizacion %><br />
    <%= f.text_field :autorizacion %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br />
    <%= f.text_area :direccion %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br />
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :celular %><br />
    <%= f.text_field :celular %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/formularios/edit.html.erb
<h1>Editing formulario</h1>

<%= render 'form' %>

<%= link_to 'Show', @formulario %> |
<%= link_to 'Back', formularios_path %>

app/views/formularios/index.html.erb
<h1>Listing formularios</h1>

<table>
  <tr>
    <th>Mascota</th>
    <th>Usuario</th>
    <th>Revisado</th>
    <th>Aceptado</th>
    <th>Ocupacion</th>
    <th>Dependencia</th>
    <th>Autorizacion</th>
    <th>Direccion</th>
    <th>Telefono</th>
    <th>Celular</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @formularios.each do |formulario| %>
  <tr>
    <td><%= formulario.mascota_id %></td>
    <td><%= formulario.usuario_id %></td>
    <td><%= formulario.revisado %></td>
    <td><%= formulario.aceptado %></td>
    <td><%= formulario.ocupacion %></td>
    <td><%= formulario.dependencia %></td>
    <td><%= formulario.autorizacion %></td>
    <td><%= formulario.direccion %></td>
    <td><%= formulario.telefono %></td>
    <td><%= formulario.celular %></td>
    <td><%= link_to 'Show', formulario %></td>
    <td><%= link_to 'Edit', edit_formulario_path(formulario) %></td>
    <td><%= link_to 'Destroy', formulario, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Formulario', new_formulario_path %>

app/views/formularios/new.html.erb
<h1>New formulario</h1>

<%= render 'form' %>

<%= link_to 'Back', formularios_path %>

app/views/formularios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Mascota:</b>
  <%= @formulario.mascota.nombre %>
</p>

<p>
  <b>Usuario:</b>
  <%= @formulario.usuario.email %>
</p>

<p>
  <b>Revisado:</b>
  <%= @formulario.revisado %>
</p>

<p>
  <b>Aceptado:</b>
  <%= @formulario.aceptado %>
</p>

<p>
  <b>Ocupacion:</b>
  <%= @formulario.ocupacion %>
</p>

<p>
  <b>Dependencia:</b>
  <%= @formulario.dependencia %>
</p>

<p>
  <b>Autorizacion:</b>
  <%= @formulario.autorizacion %>
</p>

<p>
  <b>Direccion:</b>
  <%= @formulario.direccion %>
</p>

<p>
  <b>Telefono:</b>
  <%= @formulario.telefono %>
</p>

<p>
  <b>Celular:</b>
  <%= @formulario.celular %>
</p>


<%= link_to 'Edit', edit_formulario_path(@formulario) %> |
<%= link_to 'Back', formularios_path %>