config/routes.rb
Animales::Application.routes.draw do
  get "user/currentUser"

  get "users/currentUser"

  resources :formularios

  devise_for :admins

  resources :admins

  devise_for :protectoras

  get "display/index"

  devise_for :users, :controllers => { :omniauth_callbacks => "display#facebook" }

  resources :protectoras

  resources :mascota
  
  root :to => 'display#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html> 
<html>
<head>
  
		<title>Animales</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>


<%
@formsCount = 0
if  current_user && !current_protectora && !current_admin
@barcreator = 0
@barcreadorID = current_user.id

elsif current_protectora && !current_admin
	@barcreator = 1
	@barcreadorID = current_protectora.id
    
elsif current_admin 
	@barcreator = 2
	@barcreadorID = current_admin.id
    

end
if  current_user && !current_protectora && !current_admin
  @currentUser = current_user
   @creadorID = current_user.id
   @creator = 0
   @currentUserPass = true

 elsif current_protectora && !current_admin
   @currentUser = current_protectora

   @creator = 1
   @creadorID = current_protectora.id 
   @currentUserPass = true

 elsif current_admin 
   @currentUser = current_admin

   @creator = 2
   @creadorID = current_admin.id
   @currentUserPass = true

 end


@misMascotas = Mascotum.find(:all, :conditions => {:protectora => @creadorID,:creator=>@creator})

@mascotasDestacadas = Mascotum.find(:all, :conditions => {:destacado => true})

%>
</head>



<body>
	<div id="user-nav">
			<div id="user_nav">
			  USUARIO :  <% if user_signed_in? %>
			 Signed in as <b><%= current_user.name %>.</b> Not you?
			    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
			  <% else %>
			    <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>

			  <% end %>
			</div>
			<div id="protectora_nav">
			  PROTECTORA: <% if protectora_signed_in? %>
			   Signed in as <%= current_protectora.email %>. Not you?
			    <%= link_to "Sign out", destroy_protectora_session_path, :method => :delete %>
			  <% else %>
			    <%= link_to "Sign up", new_protectora_registration_path %> or <%= link_to "sign in", new_protectora_session_path %>
			  <% end %>
			</div>

			<div id="admin_nav">
			  Admin: <% if admin_signed_in? %>
			   Signed in as <%= current_admin.email %> Not you?
			    <%= link_to "Sign out", destroy_admin_session_path, :method => :delete %>
			  <% else %>
			    <%= link_to "Sign up", new_admin_registration_path %> or <%= link_to "sign in", new_admin_session_path %>
			  <% end %>
			</div>
		</div>
	</div>
	<div id="page">
			<a href="/">	<div id="bandera"><%= image_tag "bandera.png"%></div>
	<div id="logo"><%= image_tag "logo.png"%>
		</div></a>
			
			
			<% if user_signed_in? %>
			
			    <%= link_to destroy_user_session_path, :method => :delete do%>
		<div id="registrate" > 
			<div id="user-name">
		<%= current_user.name %> 
			</div>
			<div id="flag-user" style="padding-left:25px; padding-top:5px; margin-top: -25px;">
			Log Out
			</div>
		</div>
		<%end%>
			  <% else %>
			<%= link_to user_omniauth_authorize_path(:facebook) do %>
		
		    
			
			<div id="registrate">
				
				<div id="flag-user" style="padding-left:20px; padding-top:5px;">
					Registrate
				</div>
			</div>
				<% end %>
			  <% end %>
	
			<% if flash[:notice] %>
						    <div id="notice"><%= flash[:notice] %></div>
						<% end %>
		
	<%= yield %>
	
	
</body>



	<div id="sidebar">
		<h1 style=" margin-top:37px; margin-left:10px;"><a style="color:white;" href="/user/currentUser">Status</a></h1>
		<div id="formularios-bar">
			<% @misMascotas.each do |miMascota| %>
			<% @formsCount =  @formsCount + miMascota.formularios.count%>
			<%end%>
			<%= @formsCount%>

			
			</div>
			<div style="text-shadow: 0px 2px 3px #555; margin-left:22px;">Forms</div>
			
		<div id="mascotas-bar">
		<%= image_tag "huella.png"%>
		</div>
			<div style="text-shadow: 0px 2px 3px #555; margin-left:27px;">Pets</div>
		
	</div>


	<div id="menu">
		<ul>
		<li><a href="/">HOME</a></li>
		<li><a href="/mascota">Adoptables</a></li>
		<li>Nosotros</li>
		<li><a href="/protectoras">Protectoras</a></li>
		<li>Términos</li>
		<%= image_tag "dobleGo.png", :style => "margin-top:30px;" %>





			</ul>
	</div>

	<div id="randoms">
		<div id="mascotaRan">

			<% @mascotaRan = @mascotasDestacadas.sample%>
				<div id="adoptado-ban">
					<%= image_tag "adoptado.png" %>

				</div>
			<%= link_to @mascotaRan do %>
			<%= image_tag @mascotaRan.foto.url(:thumb) %>
			<%end%>

	</div>
		<div id="protectoraRan">
			<%@protectoraRan = Protectora.all.sample%>
				<%= link_to @protectoraRan do %>
			<%= image_tag @protectoraRan.logo.url(:thumb) %>
			<%end%>
		</div>
	</div>
<footer>
	
			<div id="protectora-nav">
	 <% if protectora_signed_in? %>
			   Sesión iniciada como <%= current_protectora.email %> No eres tú?
			    <%= link_to "Log out", destroy_protectora_session_path, :method => :delete %>
			  <% else %>
			    Eres una protectora? <%= link_to "Registrate", new_protectora_registration_path %> o <%= link_to "Inicia sesión", new_protectora_session_path %>
			  <% end %>
			</div>

	</footer>
	
	 <% if admin_signed_in? %>
			    <%= link_to "Log out ADMIN", destroy_admin_session_path, :method => :delete %>
	
		 <%end%>
		</html>